[workspace]

[package]
name = "canopie-themes"
version = "0.1.0"
edition = "2024"
publish = ["canopie"]

[workspace.dependencies]
canopie-themes-morningstar = { version = "0.1.0", path = "crates/morningstar", registry = "canopie" }

[dependencies]
canopie-themes-morningstar.workspace = true

[features]
embed = ["canopie-themes-morningstar/embed"]
